### ISSUE TITLE
Query about your code

### ISSUE THREAD

**Issue by KhadijaZahoor** [Rhuax/Mindwave-brainwaves-reader#1]
I am getting the following errors while running your code

"C:\Users\Khadija Zahoor\Anaconda3\python.exe" "C:/Users/Khadija Zahoor/Desktop/Neurosky projects Github/Mindwave-brainwaves-reader/main.py"
Nome dell'utente: rahama
Nome del task: fff
Durata del task(sec):7
Saving data...
Traceback (most recent call last):
  File "C:/Users/Khadija Zahoor/Desktop/Neurosky projects Github/Mindwave-brainwaves-reader/main.py", line 20, in <module>
    record.start()
  File "C:\Users\Khadija Zahoor\Desktop\Neurosky projects Github\Mindwave-brainwaves-reader\NeuroPy.py", line 44, in start
    threading.Thread(target=self.__packetParser(self.srl)).start()
  File "C:\Users\Khadija Zahoor\Desktop\Neurosky projects Github\Mindwave-brainwaves-reader\NeuroPy.py", line 52, in __packetParser
    p2 = binascii.hexlify(srl.read(1)).decode('ascii')
  File "C:\Users\Khadija Zahoor\Anaconda3\lib\site-packages\serial\serialwin32.py", line 283, in read
    ctypes.byref(self._overlapped_read))
TypeError: byref() argument must be a ctypes instance, not 'NoneType'
Saved

Process finished with exit code 1

Kindly guide me to resolve these.

**Comment by LazyNeko1** [comment]
The `self._overlapped_read` is reading `None`, do you have everything set up properly?
